### ISSUE TITLE
sftp.put executes successfully but file drops intermittently in the server

### ISSUE THREAD

**Issue by hemanthreddyk** [theophilusx/ssh2-sftp-client#277]
I am trying to upload 10 files sequentially to remote sftp server. All 10 sftp.put calls turns out to be successful but when I check the number of files in the remote server it always varies.
I tried executing the same with sequest module and I could see all 10 files in the remote server.
Please go through the following code snippet and let me know if I am missing something here.
https://github.com/hemanthreddyk/TestFileDrop

Observed the same behaviour in node 10.21.0 and 12.13.1.

**Comment by theophilusx** [comment]
The first thing which jumps out at me is that your approach is terribly
inefficient. With sftp connections, the slowest part is establishing the
connection. So really you want to just create one connection and then
upload multiple files (sequentially) using that connection. In your
code, your creating a new connection for every uploaded file.

There is also a second problem when creating many connections.
Establishing an SFTP connection occurs in two stages. In the first
stage, you establish an anonymous connection and then you negotiate key
exchange, cipher algorithms etc and in the second stage, you transition
to an authenticated encrypted connection which can then be used to
transfer the data.

Most SFTP servers have built in limits on the number of concurrent
connections. The default limit for openSSH is around 20, but after 10 it
starts randomly dropping some connections (at an increasing number)
until it reaches the maximum, at which time it just rejects connection
requests. As TCP connections are not dropped immediately after you
disconnect (there is a TIME_WAIT, which usually defaults to around 60
seconds), it is very easy to run into this connection limiting if your
creating new connections in a loop, especially if the files being
uploaded are very small. When it occurs, initially, you will notice
random connections being dropped or failing.

Note also that there is a warning in the README about using an
SftpClient object for multiple connections. The interaction between
event handlers and Promises is very complex - especially with handling
error events which are raised in-between promise invocations (how to
return that failure as part of a promise based API). The module tries to
handle this in a robust manner, but this can become unreliable if you
use the same SftpClient object for multiple connections i.e. doing
multiple
sftp.connect()....sftp.end()....sftp.connect()....sftp.end()....

A much better model to follow is

- Create client object with new
  - Open a connection to the remote server
    - Perform uploads, downloads, listing, etc. You can do multiple
      things, just ensure they are all done sequentially (no concurrent
      requests).
  - end connection
- dispose of object

If later you need to do more interactions with the remote server, create
a new client object.

Make the above changes to your design and I expect you will get much
more reliable results and it will be much much faster.

**Comment by frago711** [comment]
I stumbled accross a similar problem using node RED with [`node-red-contrib-sftpco`](https://github.com/fatoldsun00/node-red-contrib-sftpco) which is using `ssh2-sftp-client`.

The problem occured with a specific sftp-server which seems to have some performance issues. I also observed problems with puting only one file or several files in a queue.

I manged to get the put to work in changing the line ...

https://github.com/theophilusx/ssh2-sftp-client/blob/80746951a969a16dfed90b285f7e88b54a6b390e/src/index.js#L700

... to ... 

```js
stream.once('close', () => {
```

As I'm not deep into sftp-handling, I'm not sure if this is the correct approach, but in my case it seems to work.

**See my test case below.**

The modified code:
```js
        stream.once('close', () => {
	    console.log('!!!! CLOSED !!!! <- working code removes listeners here')
            utils.removeListeners(stream);
            if (options.autoClose === false) {
              stream.destroy();
            }
            resolve(`Uploaded data stream to ${dst}`);
            this.removeListener('error', errorListener);
            this.removeListener('close', closeListener);
        });
        stream.once('finish', () => {
            console.log('!!!! FINISHED !!!! <- original code removed listeners here')
        });
```

Results in this Log:
```
node-red_1  | DEBUG: Parser: pktLen:44,padLen:13,remainLen:32
node-red_1  | DEBUG: Parser: IN_PACKETDATA
node-red_1  | DEBUG: Parser: Decrypting
node-red_1  | DEBUG: Parser: HMAC size:32
node-red_1  | DEBUG: Parser: IN_PACKETDATAVERIFY
node-red_1  | DEBUG: Parser: Verifying MAC
node-red_1  | DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
node-red_1  | DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
node-red_1  | DEBUG[SFTP]: Parser: Response: STATUS
node-red_1  | DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
node-red_1  | DEBUG[SFTP]: Outgoing: Writing CLOSE
node-red_1  | DEBUG: Outgoing: Writing CHANNEL_DATA (0)
node-red_1  | !!!! FINISHED !!!! <- original code removed listeners here
node-red_1  | DEBUG: Parser: IN_PACKET
node-red_1  | DEBUG: Parser: Decrypting
node-red_1  | DEBUG: Parser: pktLen:44,padLen:13,remainLen:32
node-red_1  | DEBUG: Parser: IN_PACKETDATA
node-red_1  | DEBUG: Parser: Decrypting
node-red_1  | DEBUG: Parser: HMAC size:32
node-red_1  | DEBUG: Parser: IN_PACKETDATAVERIFY
node-red_1  | DEBUG: Parser: Verifying MAC
node-red_1  | DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
node-red_1  | DEBUG: Parser: IN_PACKETDATAAFTER, packet: CHANNEL_DATA (0)
node-red_1  | DEBUG[SFTP]: Parser: Response: STATUS
node-red_1  | !!!! CLOSED !!!! <- working code removes listeners here
node-red_1  | CLIENT[sftp]: Removing listener from error
node-red_1  | CLIENT[sftp]: Removing listener from close
```

**Comment by theophilusx** [comment]
If it is working when your listening for a 'close' signal rather than a
'finish' signal, I would verify the files are not being truncated at
all.

The 'close' event is supposed to be fired after the 'finish' event,
indicating the writeable stream has been closed. If you are getting a
close event before or without a finish event, it typically means the
connection/stream was closed before the data transfer was complete. It
is possible the files won't be truncated, but that could be more luck
than anything else (without a finish event, it is likely that stream
buffers are not flushed completely).

This could occur if either your network is unreliable or the remote
server is unreliable and is closing connections before they have ended.

Note that each method adds and removes close listeners, so be cautious
about which close listener is being removed when referenced in the logs.
This is all part of complexity associated with using a Promise based API
on top of an event based API (ssh2/ssh2-streams).

From that little bit of log messages you included, I'm a little
concerned that something in the code is closing the connection before
the transfer has completed. This can easily occur by missing an await or
by failing to return a promise in a 'then' block in a 'then' chain. I
see log messages about ssh2 closing the connection, but not the normal
debug log messages you should see from ssh2-sftp-client regatrding
put().


- what version of node your using?
- what version of ssh2-sftp-client are you using (or being used by node_red??
- What platform are you on?
- What platform and type of remote sftp server is it (this can sometimes
  be found by adding a debug function and see what it reports in the
  initial connection messages).
- Are you passing in a source filename, a buffer or a stream to put()?

Two things I would try are

1. Write a simple script using ssh2-sftp-client and see if you see the
same failure. This will rule out a problem with how other code is using
the module.

2. Write a simple script using ssh2 and see if you see the same
failures. If not, this would indicate an issue in ssh2-sftp-client.

There are examples of ssh2-sftp-client scripts in the example folder of
the repo and examples of using just ssh2 in the tools directory.

**Comment by frago711** [comment]
Thank you for your fast response.

At first some answers to your questions:
- node-version: 10.22.0
- ssh2-sftp-client: 5.3.1
- it's a docker container running in WSL (Ubuntu)
- remote server according to debug-messages (if I get that right): Remote ident: 'SSH-2.0-DataPowerSSH_1.1'
- I'm passing in a source filename

The order of the events seems to be fine (at first the 'finish' event and afterwards the 'close' event.). In the Log there seems to be some more action after the 'finish' event.
As I was thinking of an timing-problem I first tried to postpone only the call `utils.removeListeners(stream);` by calling it with a timeout of 2 seconds. This also worked well and I assumed that the stream is not empty when the listener ist removed during 'finish'. So I tried removing the listeners on 'close'.

The `put()` is called by node-red-contrib-sftpco as follows:

[`await sftp.put(localPath,path.posix.join(remoteFilePath,file))`](https://github.com/fatoldsun00/node-red-contrib-sftpco/blob/db3c4f0c03056b6dda139fad66480b264f922717/node-red-sftpco.js#L108)

But as you stated the problem could be the configuration of the server. Also the connection to other sftp servers (local and in the web) seem to work with the original configuration. Do you have any idea what configuration on server side could cause such a problem? The problem is that the server is working with several clients and we have to point out that this is a issue with the server.

Still I'm going to try your proposals and will post the results.

**Comment by theophilusx** [comment]
That is a complex environment you are working with. You are passing
through 3 network stacks before you have even left the host (docker ->
WSL -> Windows). I'm also not yet convinced that changing the event
handler from 'finish' to 'close' is actually the correct solution - I
think more testing is required there. A 'close' event would sort of work
just as well as a 'finish' event, though the big difference is that you
will always get a close event, even when there is an error. You only get
a finish event when the write finishes correctly. If we resolve the
promise on close events, we may be resolving promises when we should be
rejecting them. It should not matter when the event listeners are
removed as long as they are removed after a finish event. Removing them
after the close event would work just as well - bottom line is once we
get a finish event, we don't care about the stream any more. If we
remove them after 'finish', we won't see 'close' (and we would not see
error, but we don't care about errors at this point because the transfer
has finished).

Here is what I would try -

1. Upgrade to node v12. Node v10 was the first release of async/await
and there were a number of improvements in Promises and Async/Await in
v12. I also seem to recall some network enhancements and possibly some
improvements to the encryption support. At any rate, node 10 is quite
old now and LTS is node 12.

2. I would set a couple of the network related options in the config
object for the connect call. In particular, set compression to false and
set ipv4 to true (see the ssh2 documentation for the precise property
names). I have had issues with compression with some firewalls
(especially deep packet inspecting firewalls) and this might ensure
consistent network stacks across the board. In your environment, we want
as simple networking as possible.

3. As you are passing in filenames as the source data, I would change to
use fastPut() rather than put(). The fastPut() method is more efficient
and can take advantage of concurrent transfer of larger files,
increasing throughput speed. The put() method is OK, but its main
advantage is in its ability to accept buffers and streams as input. As
your not doing either of these, fastPut() is a better choice. Not all
sftp servers support fastPut(), but the majority do.

4. Put together a minimal test case script which is able to reproduce
the issue. While I suspect your issues are related to your environment
or the remote server, we need to be able to reproduce the issue reliably
in order to diagnose. It should be possible to put together a script
which is under 50 lines that I can also try testing with.

5. Put together a second minimal test script which only uses ssh2 (no
ssh2-sftp-client). If this also fails, we know that the problem (if
there is one in the code) is with the ssh2 code and is something which
will need to be dealt with upstream (which is unlikely to happen as ssh2
is currently undergoing a complete re-write - I have to update
ssh2-sftp-client to work with the new version once it is mature enough).
This will at least tell us if we are looking in the right place and
whether there is any point in pursuing further at this time.

As to what might be causing the issue on the remote server, that is
difficult to answer. There are some known bad servers out there which
simply don't behave well with the ssh2 library because they are not
fully protocol compliant (for example download.com) and we know there
are some issues with sftp servers running under Azure (they raise an
error signal every time the connection is closed, even when no error
occurs. This was one of the fixes implemented in 5.3.1). In general,
sftp servers running under Windows seem less reliable than those running
under Linux and openSSH sftp seems more compliant than some of the
commercial sftp servers. What does seem to be unusual in your case is
the fact your not seeing errors/failure messages. It is unusual to
either have files just 'vanish' or for the system to report success, but
the files not being on the remote server. The only time when I've seen
this is in environments where the network is extremely unreliable and
connections are just lost with no errors being thrown.

If you have no other choice, one work around which might help is to add
CRC checking to your script. This is not terribly efficient, but can at
least alert you to failures when nothing else does. Essentially, after
uploading the data, you download it and do a checksum of the data which
you compare to a checksum you ran on the file before upload. If the
checksums don't match, then you know something has gone wrong. Not a
great solution, but sometimes even a bad solution is better than no
solution at all.

A final 'long shot' is that you could try the code in the version-6
branch. This is where I am preparing for the ssh2 rewrite. Currently, it
still uses the same ssh2 version, but it has removed a lot of additional
error checking I added in the mainline branch.

The additional error checking was added because often, the
ssh2/ssh2-streams library returns very cryptic error messages (often,
just the word 'Failure'). This caused lots of confusion for users and
limited what error handling people could add to their client code. I
therefore added a lot of additional tests/checks to provide more
meaningful error messages. Unfortunately, this had two negative side
effects. Firstly, it had a performance impact when dealing with lots of
small files and secondly, failed to work on some sftp servers which had
really locked down security configurations (i.e. do not allow list(),
stat() and realPath() calls). The additional error checking also made
the code more complex, leading to other bugs. Removing this additional
layer of checks simplifies the code and simpler code tends to have less
errors. You could try out that code and see if you also get errors (it
has the same API as the 5.3.1 code). Note however, at some point in the
next few weeks, I will be changing this branch to use the new ssh2
re-write, at which time, the code will definitely break and become
unusable for a time. If you use this code, you need to make sure you
lock it down to a specific commit.

**Comment by frago711** [comment]
Wow great and detailed response which covers also some background. :+1:

I tried a simple script using ssh2-sftp-client based on the `put1()` in your demo.js. It did work well with the problematic server and I could not manage to reproduce the problem in a frist run.
I implemented this basic functionality directly in node RED (within a function-node) and my problem seems to be solved. 
But still I do not understand why the package I used did not work, since my code is quite similar and the obvious awaits are used.
I suspect its a combination of the sftp-server (which already had some other issues in the past) and the environment which I am using (WSL, Docker, Node-RED, packages...)
Maybe I will try some of your suggestions. They look promising and not understanding why the other package is not working is gnawing at me.

**Comment by theophilusx** [comment]
Just wondering - are you sure the original package you were using was in
fact using the latest version of ssh2-sftp-client? Perhaps it bundles an
earlier version?

I don't know anything about node-red, just shooting in the dark here!

**Comment by frago711** [comment]
Yes, I double checked that. It uses 5.3.1.
There is in fact another package which uses an older version (4.x) and has the same problem. (I did not look further into that one)

**Comment by hemanthreddyk** [comment]
> The first thing which jumps out at me is that your approach is terribly inefficient. With sftp connections, the slowest part is establishing the connection. So really you want to just create one connection and then upload multiple files (sequentially) using that connection. In your code, your creating a new connection for every uploaded file. There is also a second problem when creating many connections. Establishing an SFTP connection occurs in two stages. In the first stage, you establish an anonymous connection and then you negotiate key exchange, cipher algorithms etc and in the second stage, you transition to an authenticated encrypted connection which can then be used to transfer the data. Most SFTP servers have built in limits on the number of concurrent connections. The default limit for openSSH is around 20, but after 10 it starts randomly dropping some connections (at an increasing number) until it reaches the maximum, at which time it just rejects connection requests. As TCP connections are not dropped immediately after you disconnect (there is a TIME_WAIT, which usually defaults to around 60 seconds), it is very easy to run into this connection limiting if your creating new connections in a loop, especially if the files being uploaded are very small. When it occurs, initially, you will notice random connections being dropped or failing. Note also that there is a warning in the README about using an SftpClient object for multiple connections. The interaction between event handlers and Promises is very complex - especially with handling error events which are raised in-between promise invocations (how to return that failure as part of a promise based API). The module tries to handle this in a robust manner, but this can become unreliable if you use the same SftpClient object for multiple connections i.e. doing multiple sftp.connect()....sftp.end()....sftp.connect()....sftp.end().... A much better model to follow is - Create client object with new - Open a connection to the remote server - Perform uploads, downloads, listing, etc. You can do multiple things, just ensure they are all done sequentially (no concurrent requests). - end connection - dispose of object If later you need to do more interactions with the remote server, create a new client object. Make the above changes to your design and I expect you will get much more reliable results and it will be much much faster.



> The first thing which jumps out at me is that your approach is terribly inefficient. With sftp connections, the slowest part is establishing the connection. So really you want to just create one connection and then upload multiple files (sequentially) using that connection. In your code, your creating a new connection for every uploaded file. There is also a second problem when creating many connections. Establishing an SFTP connection occurs in two stages. In the first stage, you establish an anonymous connection and then you negotiate key exchange, cipher algorithms etc and in the second stage, you transition to an authenticated encrypted connection which can then be used to transfer the data. Most SFTP servers have built in limits on the number of concurrent connections. The default limit for openSSH is around 20, but after 10 it starts randomly dropping some connections (at an increasing number) until it reaches the maximum, at which time it just rejects connection requests. As TCP connections are not dropped immediately after you disconnect (there is a TIME_WAIT, which usually defaults to around 60 seconds), it is very easy to run into this connection limiting if your creating new connections in a loop, especially if the files being uploaded are very small. When it occurs, initially, you will notice random connections being dropped or failing. Note also that there is a warning in the README about using an SftpClient object for multiple connections. The interaction between event handlers and Promises is very complex - especially with handling error events which are raised in-between promise invocations (how to return that failure as part of a promise based API). The module tries to handle this in a robust manner, but this can become unreliable if you use the same SftpClient object for multiple connections i.e. doing multiple sftp.connect()....sftp.end()....sftp.connect()....sftp.end().... A much better model to follow is - Create client object with new - Open a connection to the remote server - Perform uploads, downloads, listing, etc. You can do multiple things, just ensure they are all done sequentially (no concurrent requests). - end connection - dispose of object If later you need to do more interactions with the remote server, create a new client object. Make the above changes to your design and I expect you will get much more reliable results and it will be much much faster.

I completely agree with what you said. 
Our use-case is just uploading a single file, so opening a new connection shouldnt be a problem. Recently after changing to ssh2-sftp-client , we had a issue where a user successfully uploaded a file, but it was not found in the server. 
After multiple manual trials with a single file we couldnt successfully reproduce this issue. 
But when tried uploading multiple files sequentially by opening a new connection each time(intentional) we noticed that some files are missing.

In case of any connection drop that occurs, instead of resolving the promise successully throwing an error will be more meaningful.

**Comment by theophilusx** [comment]
If the client is aware that the connection has been lost/dropped, it
will reject the promise. The promise will only be resolved if the
'finish' event is raised. This event is raised by the rmeote writeStream
once the data has been successfully piped. If the promise is being
resolved when the data has not been uploaded, something is making the
remote server believe all the data has been transferred.

If you want to test multiple file uploads while opening multiple
connections, you need to ensure you are creating a new SftpClient object
for each connection. Do not use the same SftpClient object for multiple
connections.

The reason for this is a little complicated. Basically, Sftpclient has
some global error and close handlers to try an ensure any lost
connection BETWEEN method calls are caught and the connection is set
internally to false. However, if you open and close a connection
multiple times on the same SftpClient object, depending on timing, the
state of these event handlers can become messed up. This is avoided by
ensuring a new Sftpclient object with each new connection.

I have stress tested the client on multiple different platforms with
different sftp servers and on different networks and cannot reproduce
the 'lost files' you have reported. From memory, your tests with
multiple connections were using the same SftpClient object. You need to
re-test, ensuring a new SftpClient object for each connection and see if
you can reproduce the issue. If you can, provide a complete minimal test
script which reproduces the problem and I can try running it against my
test systems.

**Comment by hemanthreddyk** [comment]
As you suggested we tried using a new SftpClient object for each connection and it did not make any difference, we still see few files missing in the remote server.
Out of curiosity after uploading the file we added an extra exists check (sftpClient.exists), after that we observed that all the files are getting uploaded successfully.
We tested this behaviour by varying the number of files 10, 20, 50 and 100, in all the cases all the files got uploaded successfully. 
``` 
 async upload (remotePath, fileStream) {
    let sftpClient
    try {
      sftpClient = await this.getConnection()
      console.log('Uploading the file to the remote SFTP server')
      const response = await sftpClient.put(fileStream, remotePath)
      console.log('Finished uploading the file,', response)
      const isFileExists = await sftpClient.exists(remotePath)
      console.log('file-exists', isFileExists)
    } catch (error) {
      console.log(error)
      throw error
    } finally {
      if (sftpClient) {
        await sftpClient.end()
        console.log('connection ended successfully')
      }
    }
  }
```

File upload without exists check -> could see few files missing out of 10
<img width="928" alt="Screenshot 2020-11-04 at 3 56 24 PM" src="https://user-images.githubusercontent.com/10864873/98100301-aa00ea80-1eb6-11eb-91b1-d6f453c73b7b.png">

File upload with exists check -> all 10 files are uploaded successfully
<img width="909" alt="Screenshot 2020-11-04 at 3 57 51 PM" src="https://user-images.githubusercontent.com/10864873/98100350-bdac5100-1eb6-11eb-84d4-356871e38831.png">

One more interesting part is irrespective of the result of sftp.exists file uploads were always successful, I tried intentionally passing a wrong path to sftp.exists.

Could you explain why adding an extra sftp.exists call is making sure that files get uploaded successfully to the remote server?

**Comment by theophilusx** [comment]
No, I have no idea why you would see the files uploaded successfully
when you include an exists() call and not when you don't. My guess would
be some sort of timing issue i.e. the call to end() is occurring before
the upload has completed and adding the exist() call adds sufficient
time to ensure the upload has completed. This shouldn't occur, but the
behaviour you are seeing is similar to behaviour I've seen when people
have called end() before put/fastput has completed (which should not
happen with your await calls).

I would try moving the end() from the finally block and putting it at
the end of the main try block with an await and see if that makes any
difference. It could be some weird interaction between try/finally and async?

**Comment by hemanthreddyk** [comment]
Instead of sftp.exists call I also tried adding a sleep of 5sec before ending the connection , even it worked flawlessly.

```
const sleep = (time) => {
  return new Promise(resolve => {
    setTimeout(resolve, time)
  })
}
```

**Comment by theophilusx** [comment]
Even though you found no difference when you used a new SftpClient for
each connection, I can only stress that you should not re-use the same
SftpClient for multiple connections. This is not supported and results
will be unpredictable.

I'm fairly confident your running into the connection limiting facility
which exists in most remote sftp servers. The addition of an extra call
(like exists()) or adding of a small sleep time are strong indicators
this is the issue. Adding the additional call or the sleep reduces the
speed at which your making the connections, preventing the limiter from
being triggered.

Most sftp servers have a rate limiting scheme which has a very small
number of allowed connections from an IP in a small amount of time. I
have seen this triggered with less than 10 connections in a brief
period. It is also common for servers to not throw an error when they do
this (rationale is not to provide details to client in case it is a
deliberate 'attack'). This means that when the rate limiting is
triggered, no error is raised and therefore the client believes the
upload has completed (plus, because your re-using the Sftpclient object,
I'm not confident all error handlers are active).

Move your connect() and end() call outside of your loop. Return the
response as an explicit return from your upload function (so there is a
value in the returned Promise) and remove the additional exist() or
sleep calls.

Make sure your not using any of the array comprehension functions, like
array.forEach() to call your upload function as these functions are not
async safe. Test again with only a single connection used for all the
uploads and I suspect you will not see 'missing' files.

If you want further confirmation, add a sleep outside of the upload()
call in your original code to slow down how fast you are creating connections and I suspect
that would work as well. You can probably vary the time of the sleep
until you find the 'cutoff' where connections get dropped (and uploaded
files go missing). The common values used for TIME_WAIT are 30sec, 1 min
or 2 min (RFC default is 2 min). Common trigger level for sftp rate
limiting is 10 unauthenticated connections. If your connections are
short lived, it is very easy to cross this line (assume your connection
'lives' for 2 minutes after you call sftp.end()). This also means that
during testing, you should wait at least 2 minutes between test runs.

**Comment by rvravi** [comment]
@theophilusx I have tried sftp.fastPut in place of sftp.put in the code snippet shared by @hemanthreddyk and i could see that all the files are getting uploaded successfully.
By this i feel there is no connection restrictions from the sftp server side which is causing this issue.
I have also tried sftp.put without any time delay and noticed there are files that gets missed in some random order.
I suspect there is something weird happening between the sftp.put and sftp.end which could be causing this issue because if i just add a small time delay of 5ms also it works fine as expected.
**Note: We can't use the same connection for all the files because our use case requires us to create a new connection every time and upload the file.**

**Comment by theophilusx** [comment]
Without a reproducible test case, I cannot diagnose this issue further.
It could be an issue with the way the ssh2 and the ssh2-streams module
in particular interact. However, as the ssh2-streams module has now bene
deprecated and the ssh2 module is under-going a complete re-write, even
if we did manage to identify the underlying cause, it is unlikely to be
fixed.

My only suggestion is that if you cannot use fastput, you leave a small
timeout in the code to slow down the speed of connections for put() and
wait for version 6.x of ssh2-sftp-client, which will be based on the new
ssh2 library. Unfortunately, I cannot give a timeline on when that new
version will be available.
