### ISSUE TITLE
Get DST WriteStream is resolved before writeStream is done

### ISSUE THREAD

**Issue by lykalabrada** [theophilusx/ssh2-sftp-client#371]
Hi, I'm using the latest version 7.2.0 but I'm not able to use the file right away after DST. My workaround for now is to add sleep/timeout function to wait for around 500ms before using the file, but I don't want to do this because I don't know how long it'll take for bigger files.
Please see my code below:
```
try {
        const sftp = new Client()
        await sftp.connect(sftpConfig)
        const writeStream = gcsBucket.file(path).createWriteStream() // GCS bucket writeStream
        const data = await sftp.get(sftpPath, writeStream)
        /* // Work around
        const timeout = () => new Promise(resolve => setTimeout(resolve, 500))
        await timeout() */
    } catch (error) {
      ....
    } finally {
      await sftp.end()
    }
```
- ssh2-sftp-client 7.2.0
- Node version 14.0.0
- Windows

I also tried downgrading to 7.1.0 and 7.0.4 but none of them work.
Please help. Thank you.

[Note: ] I was previously using version 6.0.1 and never had this issue.

**Comment by theophilusx** [comment]
Thanks for reporting the issue.

I suspect I know what the problem is. Fixing it is slightly more
challenging.

At the moment, the promise resolves when reading the source stream ends
rather than when the write stream is closed. This is done because in
some use cases, the client code sets autoClose on the write stream to
false and sets the pipe options to not close the write stream once the
data has been piped. This is useful, for example, you want to use the
same write stream to stream multiple files or you want to pipe the write
stream into other streams. The problem is that it means we cannot just
use the close event on the write stream to resolve the promise.

The problem is, in a 'normal' use case, this means the promise has
resolved before the system has actually closed the write stream. Most of
the time, this is not an issue, but sometimes, as in your case, if you
try to access the destination file immediately after the promise closes
and that destination file is on a slightly slower media (such as a cloud
bucket), it is possible the stream has not yet cleaned up and access
fails.

The bad news is fixing this is going to be a little tricky and take me a
few days.

The good news is that your workaround is unlikely to be affected by the
size of the file. The 500ms is just bying some additional time for node
to cleanup the write stream before you try to access the file. The time
it takes to do this is not related to the size of the file.

I will try to implement a fix over the weekend. Once I do, I'll let you
know. It would be great if you can then test to see if it fixes your
issue.

**Comment by lykalabrada** [comment]
Thank you so much @theophilusx! I will definitely test when the fix is ready.

**Comment by theophilusx** [comment]
OK, I've made a small change which should fix the issue. Now, if you
call get() and do not pass in a options.pipeOptions.end: false property,
the get() method will resolve when the write stream emits a close event.
If an options.pipeOptions.end: false property is passed in, the method
will use the 'end' event emitted by the reader (previous behaviour).

This change has been pushed to the repository, so if you could test to
see if it resolves your issue, that would be great. Let me know and if
it works, I'll push a new 7.2.1 version to npmjs.com

**Comment by lykalabrada** [comment]
I just testedt the updated code but same thing is happening. It's going thru `resolve(wtr);` (same with previous code) but I don't know why the response is still early.

**Comment by lykalabrada** [comment]
I tried to resolve to both write stream and read steam, but the result is same.

**Comment by theophilusx** [comment]
I think that was my error. The test was returning true for
options.pipeOptions.end = false when it should have returned false. I've
changed it and pushed the change. Please update and try testing again.

If it still fails, can you add a debuging function to the config options
and then post the result.

**Comment by lykalabrada** [comment]
The logic seems to work now but it still fails and the function is never resolved.
However I think I found the issue with the writer `close` event, replacing this code `wtr.once('close')` with `wtr.once('finish')` seems to do the trick 🤩

**Comment by theophilusx** [comment]
Have updated code to resolve on finish rather than close event for the
write stream. Let me know if this resolves your issue.

**Comment by lykalabrada** [comment]
I am not sure about the gcs control, sorry about this.
But the yeah, my issue is now fixed with the latest changes 👍 
Thank you so much for taking the time!

**Comment by theophilusx** [comment]
OK, I will push a new version to npmjs.com tomorrow.

**Comment by theophilusx** [comment]
Version 7.2.1 pushed to npmjs.com

**Comment by lykalabrada** [comment]
Thank you so much @theophilusx! Verified that it's working fine for me with the new version.
